// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm4bConversionOptions': string;
  'm4bExistingConversion': string;
}
export const cssExports: CssExports;
export default cssExports;
